#!/bin/sh

# Fixes up all file patches (in IntelliJ, right-click -> Run 'fixup')

cd ..
./gradlew fixupPaperApiFilePatches || true
./gradlew :gale-server:fixupMinecraftResourcePatches || true
./gradlew :gale-server:fixupMinecraftSourcePatches || true
./gradlew :gale-server:fixupPaperServerFilePatches || true
cd gradle-bin
