#!/bin/sh

# Runs the dev server after deleting session lock files (in IntelliJ, right-click -> Run 'runDevServerWithoutSessionLocks')

./deleteDevServerSessionLocks
cd ..
./gradlew :gale-server:runDevServer
cd gradle-bin
